name: dart_admin_wif_demo
description: Demonstrates initializing Firebase Admin SDKs using Workload Identity Federation in Dart
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_firebase_admin:
    git:
      url: https://github.com/lahirumaramba/dart_firebase_admin.git
      ref: lm-auth-fix
      path: packages/dart_firebase_admin

dev_dependencies:
  test: ^1.24.0

dependency_overrides:
  google_cloud_firestore:
    git:
      url: https://github.com/lahirumaramba/dart_firebase_admin.git
      ref: lm-auth-fix
      path: packages/google_cloud_firestore
  googleapis_storage:
    git:
      url: https://github.com/lahirumaramba/dart_firebase_admin.git
      ref: lm-auth-fix
      path: packages/googleapis_storage
  googleapis:
    git:
      url: https://github.com/lahirumaramba/googleapis.dart.git
      ref: lm-auth-fix
      path: generated/googleapis
  googleapis_auth:
    git:
      url: https://github.com/lahirumaramba/googleapis.dart.git
      ref: lm-auth-fix
      path: googleapis_auth
